-- USE RESTAURANTE; 

-- SELECT NOME, CATEGORIA FROM PRODUTOS WHERE PRECO >30; 
-- SELECT NOME, TELEFONE, DATA_NASCIMENTO FROM CLIENTES WHERE YEAR(DATA_NASCIMENTO) <1985
-- SELECT ID_PRODUTO, INGREDIENTES FROM INFO_PRODUTOS WHERE INGREDIENTES LIKE '%CARNE%'
-- SELECT NOME, CATEGORIA FROM PRODUTOS ORDER BY CATEGORIA, NOME
-- SELECT * FROM PRODUTOS ORDER BY PRECO DESC LIMIT 5
-- SELECT * FROM PRODUTOS WHERE CATEGORIA = "Prato Principal" limit 2 offset 5
-- CREATE TABLE BACKUP_PEDIDOS AS SELECT * FROM PEDIDOS
-- SELECT * FROM BACKUP_PEDIDOS





